switch: on
newhope:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/nlbp?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 1234

  mybatis: 
    configLocation: classpath:mybatis-config.xml
    modelPackage: member.info.domain
    mapperLoaction: classpath*:/**/*Mapper.xml
    daoPackage: member.info.dao